### ISSUE TITLE
Add macro to change default values

### ISSUE THREAD

**Issue by hkiel** [cpierquet/quizztex#1]
I use this package for many questions in a document. I do not want to display the jokers in any of them, so I have to put the option `Jokers=false` to each of the questions instaed of changing the property globally.

By looking at the quizztex sources I saw that I can use e.g.
`\setKVdefault[wwtbam]{Jokers=false,Decorations=false,Largeur=\linewidth-1pt}`
to change the default parameters.

Please, either add documention about this possibility or add a macro like `\newcommand{\setQuizzDefault}[1]{\setKVdefault[wwtbam]{#1}}` so that the internals can be easily changed without breaking older documents.

**Comment by cpierquet** [comment]
Hi- I need to look for that possibility, because keys are restored at the beginning of each environment...
Maybe using a starred version to ignore restoreKV... or your idea with the macro for changing defaults keys :-)

**Comment by hkiel** [comment]
That (the macro) is what I also use sucessfully here. I would be glad to see that macro incorporated.

**Comment by cpierquet** [comment]
It's done, for 0.1.4 version ;-)
![image](https://github.com/user-attachments/assets/46b95273-550e-480e-bf59-5fc95200bced)
